install:
  - set QTDIR=C:\Qt\5.13.2\mingw73_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake LR4_2.pro
  - mingw32-make
  - cd ..\..\test_code
    - dir
    - windeployqt --release tst_test_gui.exe
    - dir
 
    - .\tst_test_gui.exe -xunitxml > test_code.xml
